import { z } from 'zod';

export const productIntelligenceSchema = z.object({
  category: z.enum([
    't-shirt',
    'shirt',
    'top',
    'jacket',
    'jumper',
    'dress',
    'skirt',
    'trousers',
    'shoes',
    'bag',
    'other',
    'unknown',
  ]),
  fit: z.enum(['slim', 'regular', 'relaxed', 'oversized', 'unknown']),
  shoulderConstruction: z.enum([
    'standard',
    'drop-shoulder',
    'raglan',
    'sleeveless',
    'not-applicable',
    'unknown',
  ]),
  silhouette: z.enum([
    'tapered',
    'straight',
    'boxy',
    'fitted',
    'flared',
    'not-applicable',
    'unknown',
  ]),
  length: z.enum([
    'cropped',
    'short',
    'standard',
    'long',
    'not-applicable',
    'unknown',
  ]),
  neckline: z.enum([
    'crew',
    'v-neck',
    'henley',
    'collared',
    'scoop',
    'high-neck',
    'not-applicable',
    'unknown',
  ]),
  sleeveFit: z.enum([
    'fitted',
    'regular',
    'loose',
    'sleeveless',
    'not-applicable',
    'unknown',
  ]),
  fabricWeight: z.enum([
    'light',
    'medium',
    'heavy',
    'not-applicable',
    'unknown',
  ]),
  stretch: z.enum([
    'none',
    'low',
    'medium',
    'high',
    'not-applicable',
    'unknown',
  ]),
  styleContexts: z.array(z.string().trim().min(1)).max(8),
  visualEffects: z.array(z.string().trim().min(1)).max(8),
  confidence: z.number().min(0).max(1),
  evidence: z.array(z.string().trim().min(1)).min(1).max(8),
});

export type ProductIntelligence = z.infer<typeof productIntelligenceSchema>;
